Exercise on Functions
Task-1 

In [1]:
def meters_to_feet(meters):
    """Convert meters to feet."""
    return meters * 3.28084

def feet_to_meters(feet):
    """Convert feet to meters."""
    return feet / 3.28084

def kilograms_to_pounds(kg):
    """Convert kilograms to pounds."""
    return kg * 2.20462

def pounds_to_kilograms(lbs):
    """Convert pounds to kilograms."""
    return lbs / 2.20462

def liters_to_gallons(liters):
    """Convert liters to gallons."""
    return liters * 0.264172

def gallons_to_liters(gallons):
    """Convert gallons to liters."""
    return gallons / 0.264172

def main():
    """Main function to handle user input and perform conversions."""
    print("Unit Converter: Length, Weight, and Volume")
    print("1. Length (Meters to Feet and Feet to Meters)")
    print("2. Weight (Kilograms to Pounds and Pounds to Kilograms)")
    print("3. Volume (Liters to Gallons and Gallons to Liters)")
    
    try:
        choice = int(input("Choose conversion type (1-3): "))
        if choice == 1:
            unit = input("Convert from meters (m) or feet (ft): ").strip().lower()
            value = float(input("Enter the value to convert: "))
            if unit == "m":
                print(f"{value} meters is {meters_to_feet(value):.2f} feet")
            elif unit == "ft":
                print(f"{value} feet is {feet_to_meters(value):.2f} meters")
            else:
                print("Invalid unit for length conversion.")
        elif choice == 2:
            unit = input("Convert from kilograms (kg) or pounds (lbs): ").strip().lower()
            value = float(input("Enter the value to convert: "))
            if unit == "kg":
                print(f"{value} kilograms is {kilograms_to_pounds(value):.2f} pounds")
            elif unit == "lbs":
                print(f"{value} pounds is {pounds_to_kilograms(value):.2f} kilograms")
            else:
                print("Invalid unit for weight conversion.")
        elif choice == 3:
            unit = input("Convert from liters (L) or gallons (gal): ").strip().lower()
            value = float(input("Enter the value to convert: "))
            if unit == "l":
                print(f"{value} liters is {liters_to_gallons(value):.2f} gallons")
            elif unit == "gal":
                print(f"{value} gallons is {gallons_to_liters(value):.2f} liters")
            else:
                print("Invalid unit for volume conversion.")
        else:
            print("Invalid choice. Please select a valid option (1-3).")
    except ValueError:
        print("Invalid input. Please enter a numerical value.")

if __name__ == "__main__":
    main()


Unit Converter: Length, Weight, and Volume
1. Length (Meters to Feet and Feet to Meters)
2. Weight (Kilograms to Pounds and Pounds to Kilograms)
3. Volume (Liters to Gallons and Gallons to Liters)


Choose conversion type (1-3):  2
Convert from kilograms (kg) or pounds (lbs):  kg
Enter the value to convert:  50.9


50.9 kilograms is 112.22 pounds


Task 2

In [2]:
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """Returns the maximum value from a list of numbers."""
    return max(numbers)

def find_minimum(numbers):
    """Returns the minimum value from a list of numbers."""
    return min(numbers)

def main():
    """Main function to execute the program."""
    operations = {
        '1': ('Sum', calculate_sum),
        '2': ('Average', calculate_average),
        '3': ('Maximum', find_maximum),
        '4': ('Minimum', find_minimum)
    }
    
    print("Select an operation:")
    for key, value in operations.items():
        print(f"{key}. {value[0]}")
    
    choice = input("Enter the number of your choice: ")
    
    if choice not in operations:
        print("Invalid choice. Please select a valid option.")
        return
    
    try:
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            raise ValueError("The list cannot be empty.")
        
        operation_name, operation_func = operations[choice]
        result = operation_func(numbers)
        print(f"The {operation_name.lower()} of the numbers is: {result}")
    
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values.")
    
if __name__ == "__main__":
    main()


Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter the number of your choice:  2
Enter a list of numbers separated by spaces:  1 2 3 4 5


The average of the numbers is: 3.0


4.2 Exercise on List Manipulation
1. Extract Every Other Element

In [3]:
def extract_every_other(lst):
    """Returns a new list containing every other element from the original list."""
    return lst[::2]

# Example usage
if __name__ == "__main__":
    user_input = input("Enter a list of numbers separated by spaces: ")
    try:
        numbers = list(map(int, user_input.split()))
        print("Every other element:", extract_every_other(numbers))
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


Enter a list of numbers separated by spaces:  1 2 3 4 5


Every other element: [1, 3, 5]


2. Slice a Sublist

In [4]:
def extract_every_other(lst):
    """Returns a new list containing every other element from the original list."""
    return lst[::2]

def reverse_list(lst):
    """Returns a reversed list using slicing."""
    return lst[::-1]

def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end+1]

# Example usage
if __name__ == "__main__":
    user_input = input("Enter a list of numbers separated by spaces: ")
    try:
        numbers = list(map(int, user_input.split()))
        print("Every other element:", extract_every_other(numbers))
        print("Reversed list:", reverse_list(numbers))
        
        start = int(input("Enter the starting index: "))
        end = int(input("Enter the ending index: "))
        print("Sublist:", get_sublist(numbers, start, end))
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


Enter a list of numbers separated by spaces:  1 2 3 4 5 


Every other element: [1, 3, 5]
Reversed list: [5, 4, 3, 2, 1]


Enter the starting index:  2
Enter the ending index:  4


Sublist: [3, 4, 5]


3. Reverse a List Using Slicing

In [5]:
def reverse_list(lst):
    """Returns a reversed list using slicing."""
    return lst[::-1]

# Example usage
if __name__ == "__main__":
    user_input = input("Enter a list of numbers separated by spaces: ")
    try:
        numbers = list(map(int, user_input.split()))
        print("Reversed list:", reverse_list(numbers))
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


Enter a list of numbers separated by spaces:  1 2 3 4 5


Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [6]:
def remove_first_last(lst):
    """Returns a sublist without the first and last elements using slicing."""
    return lst[1:-1]

# Example usage
if __name__ == "__main__":
    user_input = input("Enter a list of numbers separated by spaces: ")
    try:
        numbers = list(map(int, user_input.split()))
        print("Sublist without first and last elements:", remove_first_last(numbers))
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


Enter a list of numbers separated by spaces:  1 2 3 4 5 6


Sublist without first and last elements: [2, 3, 4, 5]


5. Get the First n Elements

In [7]:
def get_first_n(lst, n):
    """Returns the first n elements of the list using slicing."""
    return lst[:n]

# Example usage
if __name__ == "__main__":
    user_input = input("Enter a list of numbers separated by spaces: ")
    try:
        numbers = list(map(int, user_input.split()))
        
        n = int(input("Enter the number of first elements to extract: "))
        print("First n elements:", get_first_n(numbers, n))
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

Enter a list of numbers separated by spaces:  1 2 3 4 5 
Enter the number of first elements to extract:  3


First n elements: [1, 2, 3]


6. Extract Elements from the End

In [9]:
def get_last_n(lst, n):
    return lst[-n:]

# Ask user for input
user_input = input("Enter a list of elements (comma-separated): ")
lst = [int(x) for x in user_input.split(",")]

n = int(input("Enter the number of elements to extract from the end: "))

result = get_last_n(lst, n)
print(f"The last {n} elements are: {result}")


Enter a list of elements (comma-separated):  1, 2, 3, 4, 5
Enter the number of elements to extract from the end:  3


The last 3 elements are: [3, 4, 5]


Extract Elements in Reverse Order

In [75]:
def reverse_skip(lst):
    return lst[-2::-2]

# Ask user for input
user_input = input("Enter a list of elements (comma-separated): ")
lst = [int(x) for x in user_input.split(",")]

result = reverse_skip(lst)
print(f"The list of elements in reverse order, skipping one element in between: {result}")


Enter a list of elements (comma-separated):   1, 2, 3, 4, 5, 6


The list of elements in reverse order, skipping one element in between: [5, 3, 1]


4.3 Exercise on Nested List
1. Flatten a Nested List

In [11]:
def flatten(lst):
    flattened_list = []
    for sublist in lst:
        flattened_list.extend(sublist)
    return flattened_list

# Ask user for input
user_input = input("Enter a nested list: ")

# Convert the input string to an actual list using eval (ensure input is properly formatted)
nested_lst = eval(user_input)

# Call the flatten function
result = flatten(nested_lst)
print(f"The flattened list is: {result}")


Enter a nested list:   [[1, 2], [3, 4], [5]]


The flattened list is: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [16]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]  # Navigate through the nested list using indices
    return element

# Ask the user for a nested list
nested_list_input = input("Enter a nested list: ")

# Convert the input string into an actual list
nested_list = eval(nested_list_input)

# Ask the user for a list of indices
indices_input = input("Enter a list of indices: ")

# Convert the input string into a list of indices
indices = eval(indices_input)

# Get the element using the provided indices
element = access_nested_element(nested_list, indices)

print("The element at the specified position is:", element)


Enter a nested list:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Enter a list of indices:   [1, 2]


The element at the specified position is: 6


3. Sum of All Elements in a Nested List

In [19]:
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):  # Check if the element is a list
            total += sum_nested(element)  # Recursively sum the nested list
        else:
            total += element  # Add the element to the total if it's not a list
    return total

# Ask the user for input
input_string = input("Enter a nested list: ")
try:
    # Convert the input string into a Python list using eval()
    nested_list = eval(input_string)
    # Ensure the input is a list
    if isinstance(nested_list, list):
        print("The sum of all elements is:", sum_nested(nested_list))
    else:
        print("Please enter a valid nested list.")
except (SyntaxError, NameError):
    print("Invalid input! Please enter a valid nested list.")


Enter a nested list:   [[1, 2], [3, 2], [4, 5]]


The sum of all elements is: 17


4. Remove Specific Element from a Nested List

In [24]:
def remove_element(lst, elem):
    # Create a new list to store the result
    result = []
    
    # Iterate over each element in the list
    for element in lst:
        if isinstance(element, list):  # If the element is a list, recurse into it
            result.append(remove_element(element, elem))
        elif element != elem:  # If the element is not the one to remove, add it to the result
            result.append(element)
    
    return result

# Ask the user for input
input_string = input("Enter a nested list: ")

try:
    # Convert the input string into a Python list safely using eval()
    nested_list = eval(input_string)

    # Ensure the input is a list
    if isinstance(nested_list, list):
        elem_to_remove = input("Enter the element to remove: ")
        
        # Attempt to convert the element to remove to the same type as the first element in the list
        try:
            elem_to_remove = type(nested_list[0])(elem_to_remove)
        except:
            pass  # If there's a type conversion error, keep elem_to_remove as it is

        # Call the function to remove the element and print the result
        modified_list = remove_element(nested_list, elem_to_remove)
        print("Modified list:", modified_list)
    else:
        print("Please enter a valid nested list.")
except (SyntaxError, ValueError):
    print("Invalid input! Please enter a valid nested list.")


Enter a nested list:   [1, 2, [3, 4], 5]
Enter the element to remove:  2


Modified list: [1, [3, 4], 5]


5. Find the Maximum Element in a Nested List

In [22]:
def find_max(lst):
    max_element = float('-inf')  # Initialize to negative infinity to ensure any number will be larger

    for element in lst:
        if isinstance(element, list):  # If the element is a list, recurse into it
            max_element = max(max_element, find_max(element))
        else:
            max_element = max(max_element, element)  # Compare with the current maximum

    return max_element

# Ask the user for input
input_string = input("Enter a nested list: ")

try:
    # Convert the input string into a Python list using eval()
    nested_list = eval(input_string)
    # Ensure the input is a list
    if isinstance(nested_list, list):
        print("The maximum element is:", find_max(nested_list))
    else:
        print("Please enter a valid nested list.")
except (SyntaxError, NameError):
    print("Invalid input! Please enter a valid nested list.")


Enter a nested list:   [[1, 2], [3, [4, 5]], 6]


The maximum element is: 6


6. Count Occurrences of an Element in a Nested List

In [76]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if type(item) == list:  # If item is a list, call function again
            count += count_occurrences(item, elem)
        elif item == elem:  # If item matches elem, increase count
            count += 1
    return count

# Get input from user
nested_list = eval(input("Enter a nested list: "))  # Convert input string to list
element_to_count = eval(input("Enter the element to count: "))  # Convert input to correct type

# Count occurrences and display result
print("Occurrences of", element_to_count, ":", count_occurrences(nested_list, element_to_count))


Enter a nested list:   [[1, 2], [2, 3], [2, 4]]
Enter the element to count:  2


Occurrences of 2 : 3


7. Flatten a List of Lists of Lists

In [32]:
def deep_flatten(lst):
    flattened = []
    
    for element in lst:
        if isinstance(element, list):  # If the element is a list, recurse into it
            flattened.extend(deep_flatten(element))
        else:
            flattened.append(element)  # If it's not a list, add it to the flattened list
    
    return flattened

# Ask the user for input
input_string = input("Enter a nested list: ")

try:
    # Convert the input string into a Python list using eval()
    nested_list = eval(input_string)
    # Ensure the input is a list
    if isinstance(nested_list, list):
        print("Flattened list:", deep_flatten(nested_list))
    else:
        print("Please enter a valid nested list.")
except (SyntaxError, NameError):
    print("Invalid input! Please enter a valid nested list.")


Enter a nested list:   [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [34]:
def average_nested(lst):
    # Flatten the nested list first
    def deep_flatten(lst):
        flattened = []
        for element in lst:
            if isinstance(element, list):  # If the element is a list, recurse into it
                flattened.extend(deep_flatten(element))
            else:
                flattened.append(element)  # If it's not a list, add it to the flattened list
        return flattened
    
    # Flatten the list
    flattened_list = deep_flatten(lst)
    
    # Calculate the sum and average
    total_sum = sum(flattened_list)
    count = len(flattened_list)
    
    # Calculate and return the average
    if count == 0:  # Avoid division by zero
        return 0
    return total_sum / count

# Ask the user for input
input_string = input("Enter a nested list: ")

try:
    # Convert the input string into a Python list using eval()
    nested_list = eval(input_string)
    # Ensure the input is a list
    if isinstance(nested_list, list):
        print("The average of all elements is:", average_nested(nested_list))
    else:
        print("Please enter a valid nested list.")
except (SyntaxError, NameError):
    print("Invalid input! Please enter a valid nested list.")


Enter a nested list:   [[1, 2], [3, 4], [5, 6]]


The average of all elements is: 3.5


To - Do - NumPy
Basic Vector and Matrix Operation with Numpy
Problem-1: Array Creation
1. Initialize an empty array with size 2X2.

In [35]:
import numpy as np

In [36]:
# Initialize an empty 2x2 array
array_2x2_empty = np.empty((2, 2))

print(array_2x2_empty)


[[0.00000000e+000 3.56033886e-307]
 [2.33647355e-307 0.00000000e+000]]


 2. Initialize an all one array with size 4X2.

In [37]:
# Initialize a 4x2 array with ones
array_4x2_ones = np.ones((4, 2))

print(array_4x2_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.

In [38]:
array = np.full((4, 2), 7)

print(array)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


4. Return a new array of zeros with same shape and type as a given array.

In [39]:
original_array = np.array([[1, 2], [3, 4]])

# Create a new array of zeros with the same shape and type as the original array
zeros_array = np.zeros_like(original_array)

print(zeros_array)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.

In [40]:
original_array = np.array([[1, 2], [3, 4]])

# Create a new array of ones with the same shape and type as the original array
ones_array = np.ones_like(original_array)

print(ones_array)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [41]:
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
numpy_array = np.array(new_list)

print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing
1. Create an array with values ranging from 10 to 49.

In [42]:
array = np.arange(10, 50)

print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.


In [43]:
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix_3x3 = array.reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
3. Create a 3X3 identity matrix.

In [44]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

In [45]:
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)

Random Array: [0.48886523 0.82947747 0.20408086 0.73473726 0.9963671  0.05638975
 0.93893872 0.2236125  0.78748505 0.84055418 0.68756158 0.63097056
 0.07963113 0.4156598  0.59350134 0.64419121 0.8836201  0.75379159
 0.81458951 0.01045591 0.98616172 0.4703556  0.8269174  0.1686135
 0.86313003 0.27911842 0.23236179 0.71260388 0.47699586 0.57525551]
Mean of the Array: 0.5735331519562357


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [46]:
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values in the array
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()

print("Random 10x10 Array:")
print(random_array_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
[[0.60561666 0.03339841 0.33604438 0.6259504  0.22618899 0.31629268
  0.32946618 0.63272694 0.58600525 0.43247992]
 [0.59681647 0.0964396  0.75943357 0.11913081 0.03000859 0.13967452
  0.97853772 0.69401134 0.8092236  0.8592613 ]
 [0.51564586 0.40419614 0.65301737 0.25502205 0.50895137 0.06698587
  0.93257446 0.02645036 0.7345679  0.61725511]
 [0.82204649 0.8868451  0.05484101 0.68999543 0.37579535 0.27840158
  0.12494018 0.90348901 0.20888287 0.4773601 ]
 [0.46226986 0.53158154 0.21153212 0.73657675 0.04621454 0.20664649
  0.23442637 0.33913982 0.09690871 0.23437353]
 [0.65328051 0.90656446 0.41639493 0.22596231 0.6881619  0.36490093
  0.477406   0.26256906 0.5001681  0.6935453 ]
 [0.15279642 0.56192061 0.01952249 0.88607186 0.35264752 0.87784786
  0.94842377 0.03707312 0.87024803 0.8767305 ]
 [0.71758587 0.67754338 0.35590747 0.15837374 0.23759978 0.69282985
  0.6391063  0.56337448 0.79884779 0.61321003]
 [0.41882734 0.52209192 0.38810931 0.63308608 0.11887708 0.5

6. Create a zero array of size 10 and replace 5th element with 1.

In [47]:
# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [48]:
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]  # or np.flip(arr)

print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [49]:
rows, cols = 5, 5  # Example size (you can change it)

# Create a 2D array filled with zeros
array = np.zeros((rows, cols), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [50]:

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [51]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [52]:
array_sum = np.add(x, y)  # or x + y

# Add the two 1D arrays
vector_sum = np.add(v, w)  # or v + w

print("Sum of x and y:\n", array_sum)
print("Sum of v and w:", vector_sum)

Sum of x and y:
 [[ 6  8]
 [10 13]]
Sum of v and w: [20 22]


2. Subtract the two array.

In [53]:
array_diff = np.subtract(x, y)  # or x - y

# Subtract the two 1D arrays
vector_diff = np.subtract(v, w)  # or v - w

print("Difference of x and y:\n", array_diff)
print("Difference of v and w:", vector_diff)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]
Difference of v and w: [-2 -2]


3. Multiply the array with any integers of your choice.

In [54]:
scalar = 3

# Multiply arrays by the scalar
x_multiplied = np.multiply(x, scalar)  # or x * scalar
y_multiplied = np.multiply(y, scalar)  # or y * scalar
v_multiplied = np.multiply(v, scalar)  # or v * scalar
w_multiplied = np.multiply(w, scalar)  # or w * scalar

print("x multiplied by", scalar, ":\n", x_multiplied)
print("y multiplied by", scalar, ":\n", y_multiplied)
print("v multiplied by", scalar, ":", v_multiplied)
print("w multiplied by", scalar, ":", w_multiplied)

x multiplied by 3 :
 [[ 3  6]
 [ 9 15]]
y multiplied by 3 :
 [[15 18]
 [21 24]]
v multiplied by 3 : [27 30]
w multiplied by 3 : [33 36]


4. Find the square of each element of the array.


In [55]:
# Find the square of each element
x_squared = np.square(x)  # or x ** 2
y_squared = np.square(y)  # or y ** 2
v_squared = np.square(v)  # or v ** 2
w_squared = np.square(w)  # or w ** 2

print("Square of x:\n", x_squared)
print("Square of y:\n", y_squared)
print("Square of v:", v_squared)
print("Square of w:", w_squared)

Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v: [ 81 100]
Square of w: [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [56]:
dot_vw = np.dot(v, w)  # or v @ w

# Dot product between x and v
dot_xv = np.dot(x, v)  # or x @ v

# Dot product between x and y
dot_xy = np.dot(x, y)  # or x @ y

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [77]:
concat_xy = np.concatenate((x, y), axis=0)  

# Concatenate v and w along columns (reshape first to make them 2D)
concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # or np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))

print("Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [58]:
try:
    result = np.concatenate((x, v), axis=0)
    print("Concatenation along rows:", result)
except Exception as e:
    print("Error while concatenating x and v along rows:", e)

# Attempt to concatenate x and v along columns (axis=1)
try:
    result = np.concatenate((x, v), axis=1)
    print("Concatenation along columns:", result)
except Exception as e:
    print("Error while concatenating x and v along columns:", e)

Error while concatenating x and v along rows: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Error while concatenating x and v along columns: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I

In [59]:

# Define the matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse to get the identity matrix
result = np.dot(A, A_inv)

# Print the result
print("A * A^-1 = \n", result)

# Verify that the result is the identity matrix
I = np.eye(2)  # Create a 2x2 identity matrix
print("Identity matrix I = \n", I)

# Check if the result is close to the identity matrix
if np.allclose(result, I):
    print("The result is the identity matrix, so A * A^-1 = I")
else:
    print("The result is not the identity matrix")


A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I = 
 [[1. 0.]
 [0. 1.]]
The result is the identity matrix, so A * A^-1 = I


2. Prove AB ̸= BA.

In [60]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print the results
print("AB = \n", AB)
print("BA = \n", BA)

# Compare AB and BA
if np.array_equal(AB, BA):
    print("AB = BA")
else:
    print("AB != BA")

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
AB != BA


3. Prove (AB)^T = B^TA^T


In [61]:
AB_transpose = np.transpose(np.dot(A, B))

# Compute the product of the transposes B^T A^T
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))

# Print both results
print("(AB)^T = \n", AB_transpose)
print("B^T A^T = \n", B_transpose_A_transpose)

# Compare (AB)^T and B^T A^T
if np.array_equal(AB_transpose, B_transpose_A_transpose):
    print("(AB)^T = B^T A^T")
else:
    print("(AB)^T != B^T A^T")

(AB)^T = 
 [[23 51]
 [13 29]]
B^T A^T = 
 [[23 51]
 [13 29]]
(AB)^T = B^T A^T


 Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [62]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([[-1], [-3], [9]])

# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Solve for X (which contains x, y, z)
X = np.dot(A_inv, B)

# Print the solution
print("The solution is:")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])


The solution is:
x = 2.0
y = 1.0
z = -2.0


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [63]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([[-1], [-3], [9]])

# Calculate the inverse of matrix A using np.linalg.inv
A_inv = np.linalg.inv(A)

# Solve for X (which contains x, y, z) using matrix multiplication
X = np.dot(A_inv, B)

# Print the solution
print("The solution is:")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])

The solution is:
x = 2.0
y = 1.0
z = -2.0


10.2 Experiment: How Fast is Numpy?
1. Element-wise Addition

In [64]:
import time
import random

# Generate two lists of size 1,000,000 with random values
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for element-wise addition using list comprehension
start_time = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using Python lists: 0.273203 seconds


In [65]:
import numpy as np
import time

# Generate two NumPy arrays of size 1,000,000 with random values
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for element-wise addition using NumPy
start_time = time.time()
result = array1 + array2  # Vectorized addition
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using NumPy: 0.004132 seconds


2. Element-wise Multiplication

In [66]:
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for element-wise multiplication using list comprehension
start_time = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using Python lists: 0.292535 seconds


In [67]:
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for element-wise multiplication using NumPy
start_time = time.time()
result = array1 * array2  # Vectorized multiplication
end_time = time.time()

# Print time taken
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using NumPy: 0.028205 seconds


3. Dot Product

In [68]:
# Generate two lists of size 1,000,000 with random values
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time taken for dot product using Python lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))  # Manual dot product
end_time = time.time()

# Print time taken
print(f"Dot product using Python lists: {dot_product}")
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

Dot product using Python lists: 2549327460
Time taken using Python lists: 0.266914 seconds


In [69]:
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time taken for dot product using NumPy
start_time = time.time()
dot_product = np.dot(array1, array2)  # Optimized NumPy dot product
end_time = time.time()

# Print time taken
print(f"Dot product using NumPy: {dot_product}")
print(f"Time taken using NumPy: {end_time - start_time:.6f} seconds")

Dot product using NumPy: -1792557913
Time taken using NumPy: 0.000958 seconds


4. Matrix Multiplication

In [70]:
size = 1000
matrix1 = np.random.randint(1, 10, (size, size))
matrix2 = np.random.randint(1, 10, (size, size))

# Measure time taken for matrix multiplication using NumPy
start_time = time.time()
result = np.dot(matrix1, matrix2)  # Optimized NumPy matrix multiplication
end_time = time.time()

# Print time taken
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time:.6f} seconds")

Time taken for matrix multiplication using NumPy: 2.681598 seconds


In [71]:
import time
import random

# Function to perform matrix multiplication for Python lists
def matrix_multiply_python(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):  # Iterate over rows of matrix1
        row = []
        for j in range(len(matrix2[0])):  # Iterate over columns of matrix2
            value = sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2)))
            row.append(value)
        result.append(row)
    return result

# Generate two matrices of size 1000x1000 with random values
size = 1000
matrix1 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]

# Measure time taken for matrix multiplication using Python lists
start_time = time.time()
result = matrix_multiply_python(matrix1, matrix2)
end_time = time.time()

# Print time taken
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")


Time taken for matrix multiplication using Python lists: 252.818624 seconds
